spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/ProductDatabase
spring.datasource.username=postgres
spring.datasource.password=chedi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false