spring.application.name=demo
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
JWT_SECRET=${JWT_SECRET}
spring.data.redis.host=${REDIS_URL}
spring.data.redis.port=${REDIS_PORT} 
spring.data.redis.password=${REDIS_PASSWORD}
# management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
spring.data.redis.repositories.enabled=false
# # Enable Prometheus endpoint
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus,health,info

# # Allow Tracing to happen (1.0 = trace every single request)
# management.tracing.sampling.probability=1.0