---
- name: Configure Web Servers
  hosts: sandbox
  # become: true
  vars:
    http_port: 80
    domain_name: example.com
    app_port: 3000

  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
        
# Install docker 
    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Create directory for Docker apt key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository to APT sources
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        state: present
        filename: docker



# Install nginx
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Ensure that nginx installed and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Put the configuration file in nginx
      ansible.builtin.template:
        src: nginx.config.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
        notify:
          - Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted